language: node_js

dist: xenial

node_js:
- "node"

script:
- npm test
- if [[ "$RUN_SAUCELABS_IT" && "$SAUCE_ACCESS_KEY" ]]; then
    npm run integration-saucelabs;
  fi

osx_image: xcode11.3

jobs:
  include:
    - os: linux
      env: RUN_SAUCELABS_IT=true # Only run SauceLabs tests in one build
    - os: osx
    - os: linux
      node_js:
        - "10"
